# Generated by Django 5.2 on 2025-04-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='location',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kapasite (m²)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sorumlu'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
    ]
