# Generated by Django 5.2 on 2025-04-06 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Arazi Adı')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Alan (Dönüm)')),
                ('location', models.CharField(max_length=255, verbose_name='Lokasyon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to=settings.AUTH_USER_MODEL, verbose_name='Sahibi')),
            ],
            options={
                'verbose_name': 'Arazi',
                'verbose_name_plural': 'Araziler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_no', models.CharField(max_length=50, verbose_name='Parsel No')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alan (Dönüm)')),
                ('soil_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Toprak Türü')),
                ('has_irrigation', models.BooleanField(default=False, verbose_name='Sulama Durumu')),
                ('coordinates', models.TextField(blank=True, null=True, verbose_name='Koordinatlar (GeoJSON)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='arazi.land', verbose_name='Arazi')),
            ],
            options={
                'verbose_name': 'Parsel',
                'verbose_name_plural': 'Parseller',
                'ordering': ['land', 'parcel_no'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irrigation_date', models.DateField(verbose_name='Sulama Tarihi')),
                ('irrigation_duration', models.DurationField(blank=True, null=True, verbose_name='Sulama Süresi')),
                ('water_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Su Miktarı (m³)')),
                ('irrigation_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sulama Yöntemi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_records', to='arazi.parcel', verbose_name='Parsel')),
            ],
            options={
                'verbose_name': 'Sulama Kaydı',
                'verbose_name_plural': 'Sulama Kayıtları',
                'ordering': ['-irrigation_date'],
            },
        ),
        migrations.CreateModel(
            name='SoilAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(verbose_name='Analiz Tarihi')),
                ('ph_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH Değeri')),
                ('organic_matter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Organik Madde (%)')),
                ('phosphorus', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Fosfor (P) (ppm)')),
                ('potassium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Potasyum (K) (ppm)')),
                ('calcium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Kalsiyum (Ca) (ppm)')),
                ('magnesium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Magnezyum (Mg) (ppm)')),
                ('iron', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Demir (Fe) (ppm)')),
                ('zinc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Çinko (Zn) (ppm)')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='soil_analyses/', verbose_name='Rapor Dosyası')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_analyses', to='arazi.parcel', verbose_name='Parsel')),
            ],
            options={
                'verbose_name': 'Toprak Analizi',
                'verbose_name_plural': 'Toprak Analizleri',
                'ordering': ['-analysis_date'],
            },
        ),
    ]
