# Generated by Django 5.2 on 2025-04-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcategory',
            name='is_expense',
        ),
        migrations.RemoveField(
            model_name='accountcategory',
            name='is_income',
        ),
        migrations.AddField(
            model_name='accountcategory',
            name='category_type',
            field=models.CharField(choices=[('income', 'Gelir'), ('expense', 'Gider'), ('other', 'Diğer')], default='expense', max_length=10, verbose_name='Kategori Tipi'),
        ),
        migrations.AddField(
            model_name='accountcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='accountcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
