# Generated by Django 5.2 on 2025-04-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorev', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worklog',
            options={'ordering': ['-start_time'], 'verbose_name': 'Çalışma Kaydı', 'verbose_name_plural': 'Çalışma Kayıtları'},
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='hours_worked',
        ),
        migrations.AddField(
            model_name='worklog',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Ödendi mi?'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ücret'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='end_time',
            field=models.DateTimeField(verbose_name='Bitiş Zamanı'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='start_time',
            field=models.DateTimeField(verbose_name='Başlangıç Zamanı'),
        ),
    ]
