# Generated by Django 5.2 on 2025-04-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arazi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tür')),
                ('variety', models.CharField(blank=True, max_length=100, null=True, verbose_name='Çeşit')),
                ('growing_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yetişme Süresi (Gün)')),
                ('planting_interval', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ekim Aralığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Fotoğraf')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField(verbose_name='Ekim Tarihi')),
                ('planting_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ekim Alanı (Dönüm)')),
                ('seed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tohum Miktarı (kg)')),
                ('planting_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ekim Yöntemi')),
                ('planting_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ekim Derinliği (cm)')),
                ('row_spacing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sıra Arası Mesafe (cm)')),
                ('estimated_harvest_date', models.DateField(blank=True, null=True, verbose_name='Tahmini Hasat Tarihi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='arazi.parcel', verbose_name='Parsel')),
            ],
            options={
                'verbose_name': 'Ekim',
                'verbose_name_plural': 'Ekimler',
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='PesticideApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(verbose_name='İlaçlama Tarihi')),
                ('pesticide_name', models.CharField(max_length=100, verbose_name='İlaç Adı')),
                ('pesticide_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlaç Türü')),
                ('active_ingredient', models.CharField(blank=True, max_length=100, null=True, verbose_name='Etken Madde')),
                ('application_dose', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uygulama Dozu')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Toplam Miktar')),
                ('application_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uygulama Yöntemi')),
                ('waiting_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bekleme Süresi (Gün)')),
                ('target_pest', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hedef Zararlı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesticide_applications', to='uretim.planting', verbose_name='Ekim')),
            ],
            options={
                'verbose_name': 'İlaçlama Kaydı',
                'verbose_name_plural': 'İlaçlama Kayıtları',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(verbose_name='Hasat Tarihi')),
                ('harvest_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hasat Miktarı (kg/ton)')),
                ('yield_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Verim (kg/dönüm)')),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nem Oranı (%)')),
                ('quality_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kalite Sınıfı')),
                ('harvest_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hasat Yöntemi')),
                ('stored_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Depolanan Miktar (kg/ton)')),
                ('sold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Satılan Miktar (kg/ton)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('planting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvest', to='uretim.planting', verbose_name='Ekim')),
            ],
            options={
                'verbose_name': 'Hasat',
                'verbose_name_plural': 'Hasatlar',
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='FertilizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilization_date', models.DateField(verbose_name='Gübreleme Tarihi')),
                ('fertilizer_name', models.CharField(max_length=100, verbose_name='Gübre Adı')),
                ('fertilizer_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gübre Türü')),
                ('application_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Uygulama Miktarı (kg/dönüm)')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Toplam Miktar (kg)')),
                ('application_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uygulama Yöntemi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilization_records', to='uretim.planting', verbose_name='Ekim')),
            ],
            options={
                'verbose_name': 'Gübreleme Kaydı',
                'verbose_name_plural': 'Gübreleme Kayıtları',
                'ordering': ['-fertilization_date'],
            },
        ),
        migrations.CreateModel(
            name='PlantingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_planting_date', models.DateField(verbose_name='Planlanan Ekim Tarihi')),
                ('planned_harvest_date', models.DateField(blank=True, null=True, verbose_name='Planlanan Hasat Tarihi')),
                ('planned_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Planlanan Tohum Miktarı (kg)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planting_plans', to='arazi.parcel', verbose_name='Parsel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planting_plans', to='uretim.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ekim Planı',
                'verbose_name_plural': 'Ekim Planları',
                'ordering': ['planned_planting_date'],
            },
        ),
        migrations.AddField(
            model_name='planting',
            name='planting_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planting', to='uretim.plantingplan', verbose_name='Ekim Planı'),
        ),
        migrations.AddField(
            model_name='planting',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='uretim.product', verbose_name='Ürün'),
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marka')),
                ('certificate_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sertifika No')),
                ('lot_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lot No')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tedarikçi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='uretim.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Tohum',
                'verbose_name_plural': 'Tohumlar',
                'ordering': ['product__name', 'brand'],
            },
        ),
        migrations.AddField(
            model_name='planting',
            name='seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantings', to='uretim.seed', verbose_name='Tohum'),
        ),
    ]
