# Generated by Django 5.2 on 2025-04-08 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('sulama', 'Sulama'), ('gubreleme', 'Gübreleme'), ('ilaclama', 'İlaçlama'), ('yabancı_ot', 'Yabancı Ot Temizliği'), ('toprak_hazirligi', 'Toprak Hazırlığı'), ('diger', 'Diğer')], max_length=20)),
                ('maintenance_date', models.DateField()),
                ('area', models.DecimalField(decimal_places=2, help_text='Bakım yapılan alan (dekar)', max_digits=10)),
                ('weather_condition', models.CharField(blank=True, max_length=100)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fertilizer', models.CharField(blank=True, max_length=100)),
                ('pesticide', models.CharField(blank=True, max_length=100)),
                ('water_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Su miktarı (m³)', max_digits=10, null=True)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('equipment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='uretim.planting')),
            ],
            options={
                'verbose_name': 'Bakım Kaydı',
                'verbose_name_plural': 'Bakım Kayıtları',
                'ordering': ['-maintenance_date'],
            },
        ),
    ]
