# Generated by Django 5.2 on 2025-04-06 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arazi', '0001_initial'),
        ('hayvan', '0001_initial'),
        ('uretim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kıyaslama Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('metric_type', models.CharField(max_length=50, verbose_name='Metrik Tipi')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bölge')),
                ('year', models.PositiveIntegerField(verbose_name='Yıl')),
                ('season', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sezon')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Değer')),
                ('unit', models.CharField(max_length=50, verbose_name='Birim')),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kaynak')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('animal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benchmarks', to='hayvan.animaltype', verbose_name='Hayvan Türü')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benchmarks', to='uretim.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Kıyaslama',
                'verbose_name_plural': 'Kıyaslamalar',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dashboard Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('layout', models.JSONField(blank=True, null=True, verbose_name='Yerleşim')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Sahibi')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['owner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LandProductivityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yıl')),
                ('season', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sezon')),
                ('area_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kullanılan Alan (Dönüm)')),
                ('total_harvest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Toplam Hasat (kg/ton)')),
                ('yield_per_dunum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dönüm Başına Verim')),
                ('revenue_per_dunum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dönüm Başına Gelir')),
                ('cost_per_dunum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dönüm Başına Maliyet')),
                ('profit_per_dunum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dönüm Başına Kar')),
                ('water_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Su Kullanımı (m³)')),
                ('fertilizer_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gübre Kullanımı (kg)')),
                ('pesticide_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='İlaç Kullanımı')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_metrics', to='arazi.land', verbose_name='Arazi')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productivity_metrics', to='arazi.parcel', verbose_name='Parsel')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_metrics', to='uretim.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Arazi Verimlilik Metriği',
                'verbose_name_plural': 'Arazi Verimlilik Metrikleri',
                'ordering': ['-year', 'land__name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rapor Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('report_type', models.CharField(choices=[('yield', 'Verim Raporu'), ('profit_loss', 'Kar/Zarar Raporu'), ('inventory', 'Envanter Raporu'), ('animal_performance', 'Hayvan Performans Raporu'), ('cost_analysis', 'Maliyet Analizi'), ('weather', 'Hava Durumu Raporu'), ('task', 'Görev Raporu'), ('custom', 'Özel Rapor')], max_length=20, verbose_name='Rapor Tipi')),
                ('query_parameters', models.JSONField(blank=True, null=True, verbose_name='Sorgu Parametreleri')),
                ('chart_settings', models.JSONField(blank=True, null=True, verbose_name='Grafik Ayarları')),
                ('visualization_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Görselleştirme Tipi')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='Zamanlanmış mı?')),
                ('schedule', models.JSONField(blank=True, null=True, verbose_name='Zamanlama')),
                ('recipients', models.JSONField(blank=True, null=True, verbose_name='Alıcılar')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Son Çalıştırma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Sahibi')),
            ],
            options={
                'verbose_name': 'Rapor',
                'verbose_name_plural': 'Raporlar',
                'ordering': ['owner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now_add=True, verbose_name='Çalıştırma Tarihi')),
                ('data', models.JSONField(verbose_name='Veri')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Özet')),
                ('status', models.CharField(max_length=20, verbose_name='Durum')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dosya Yolu')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analitik.report', verbose_name='Rapor')),
            ],
            options={
                'verbose_name': 'Rapor Sonucu',
                'verbose_name_plural': 'Rapor Sonuçları',
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='AnimalPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yıl')),
                ('period', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dönem')),
                ('average_daily_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ortalama Günlük Kilo Artışı (kg)')),
                ('feed_conversion_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Yem Dönüşüm Oranı')),
                ('mortality_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ölüm Oranı (%)')),
                ('birth_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Doğum Oranı (%)')),
                ('avg_offspring_per_female', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Dişi Başına Ortalama Yavru Sayısı')),
                ('avg_productive_lifespan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ortalama Verimli Yaşam Süresi')),
                ('avg_production', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ortalama Üretim (Süt/Yumurta vb.)')),
                ('production_unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Üretim Birimi')),
                ('avg_cost_per_animal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hayvan Başına Ortalama Maliyet')),
                ('avg_revenue_per_animal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hayvan Başına Ortalama Gelir')),
                ('profit_per_animal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hayvan Başına Kar')),
                ('total_animals', models.PositiveIntegerField(blank=True, null=True, verbose_name='Toplam Hayvan Sayısı')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='hayvan.animaltype', verbose_name='Hayvan Türü')),
            ],
            options={
                'verbose_name': 'Hayvan Performans Metriği',
                'verbose_name_plural': 'Hayvan Performans Metrikleri',
                'ordering': ['-year', 'animal_type__name'],
                'unique_together': {('animal_type', 'year', 'period')},
            },
        ),
        migrations.CreateModel(
            name='ProductPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yıl')),
                ('season', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sezon')),
                ('total_planted_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Toplam Ekim Alanı (Dönüm)')),
                ('total_harvested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Toplam Hasat Miktarı (kg/ton)')),
                ('average_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ortalama Verim (kg/dönüm)')),
                ('min_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Verim (kg/dönüm)')),
                ('max_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maksimum Verim (kg/dönüm)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Toplam Maliyet')),
                ('average_cost_per_dunum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dönüm Başına Ortalama Maliyet')),
                ('average_cost_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kg Başına Ortalama Maliyet')),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Toplam Gelir')),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ortalama Satış Fiyatı')),
                ('total_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Toplam Kar')),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kar Marjı (%)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='uretim.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Performans Metriği',
                'verbose_name_plural': 'Ürün Performans Metrikleri',
                'ordering': ['-year', 'product__name'],
                'unique_together': {('product', 'year', 'season')},
            },
        ),
    ]
