# Generated by Django 5.2 on 2025-04-06 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Irk Adı')),
                ('characteristics', models.TextField(blank=True, null=True, verbose_name='Özellikler')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Hayvan Irkı',
                'verbose_name_plural': 'Hayvan Irkları',
                'ordering': ['animal_type__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tür Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Hayvan Türü',
                'verbose_name_plural': 'Hayvan Türleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=50, unique=True, verbose_name='Küpe No')),
                ('gender', models.CharField(choices=[('M', 'Erkek'), ('F', 'Dişi')], max_length=1, verbose_name='Cinsiyet')),
                ('birth_date', models.DateField(verbose_name='Doğum Tarihi')),
                ('mother_tag_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ana Küpe No')),
                ('father_tag_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Baba Küpe No')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Geliş Tarihi')),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kaynak')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ağırlık (kg)')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Satın Alma Fiyatı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='Fotoğraf')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL, verbose_name='Sahibi')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='hayvan.animalbreed', verbose_name='Irk')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='hayvan.animaltype', verbose_name='Tür')),
            ],
            options={
                'verbose_name': 'Hayvan',
                'verbose_name_plural': 'Hayvanlar',
                'ordering': ['tag_number'],
            },
        ),
        migrations.CreateModel(
            name='AnimalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Grup Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('animals', models.ManyToManyField(related_name='groups', to='hayvan.animal', verbose_name='Hayvanlar')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_groups', to=settings.AUTH_USER_MODEL, verbose_name='Sahibi')),
            ],
            options={
                'verbose_name': 'Grup',
                'verbose_name_plural': 'Gruplar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='animalbreed',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='hayvan.animaltype', verbose_name='Tür'),
        ),
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Doğum Tarihi')),
                ('offspring_count', models.PositiveIntegerField(verbose_name='Yavru Sayısı')),
                ('male_count', models.PositiveIntegerField(default=0, verbose_name='Erkek Sayısı')),
                ('female_count', models.PositiveIntegerField(default=0, verbose_name='Dişi Sayısı')),
                ('stillborn_count', models.PositiveIntegerField(default=0, verbose_name='Ölü Doğum')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='births', to='hayvan.animal', verbose_name='Anne')),
            ],
            options={
                'verbose_name': 'Doğum',
                'verbose_name_plural': 'Doğumlar',
                'ordering': ['-birth_date'],
            },
        ),
        migrations.CreateModel(
            name='FeedRation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rasyon Adı')),
                ('age_group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yaş Grubu')),
                ('production_purpose', models.CharField(blank=True, max_length=100, null=True, verbose_name='Üretim Amacı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_rations', to='hayvan.animaltype', verbose_name='Hayvan Türü')),
            ],
            options={
                'verbose_name': 'Yem Rasyonu',
                'verbose_name_plural': 'Yem Rasyonları',
                'ordering': ['animal_type__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeding_date', models.DateField(verbose_name='Besleme Tarihi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Miktar (kg)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='hayvan.animal', verbose_name='Hayvan')),
                ('animal_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='hayvan.animalgroup', verbose_name='Grup')),
                ('feed_ration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='hayvan.feedration', verbose_name='Rasyon')),
            ],
            options={
                'verbose_name': 'Besleme Kaydı',
                'verbose_name_plural': 'Besleme Kayıtları',
                'ordering': ['-feeding_date'],
            },
        ),
        migrations.CreateModel(
            name='FeedRationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(max_length=100, verbose_name='Yem Adı')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Miktar (kg)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Birim Fiyat')),
                ('feed_ration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hayvan.feedration', verbose_name='Rasyon')),
            ],
            options={
                'verbose_name': 'Yem Rasyonu Detay',
                'verbose_name_plural': 'Yem Rasyonu Detayları',
                'ordering': ['feed_ration__name', 'feed_name'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_date', models.DateField(verbose_name='İşlem Tarihi')),
                ('procedure_type', models.CharField(choices=[('examination', 'Muayene'), ('vaccine', 'Aşı'), ('treatment', 'Tedavi'), ('surgery', 'Ameliyat'), ('other', 'Diğer')], max_length=20, verbose_name='İşlem Tipi')),
                ('diagnosis', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tanı/İşlem')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Tedavi/Uygulama')),
                ('medication', models.CharField(blank=True, max_length=200, null=True, verbose_name='İlaç')),
                ('dosage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Doz')),
                ('veterinarian', models.CharField(blank=True, max_length=200, null=True, verbose_name='Veteriner')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maliyet')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='hayvan.animal', verbose_name='Hayvan')),
            ],
            options={
                'verbose_name': 'Sağlık Kaydı',
                'verbose_name_plural': 'Sağlık Kayıtları',
                'ordering': ['-procedure_date'],
            },
        ),
        migrations.CreateModel(
            name='Offspring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Küpe No')),
                ('gender', models.CharField(choices=[('M', 'Erkek'), ('F', 'Dişi')], max_length=1, verbose_name='Cinsiyet')),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Doğum Ağırlığı (kg)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('animal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_record', to='hayvan.animal', verbose_name='Hayvan Kaydı')),
                ('birth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offspring', to='hayvan.birth', verbose_name='Doğum')),
            ],
            options={
                'verbose_name': 'Yavru',
                'verbose_name_plural': 'Yavrular',
            },
        ),
        migrations.CreateModel(
            name='ReproductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='Tarih')),
                ('reproductive_status', models.CharField(blank=True, choices=[('not_pregnant', 'Kısır'), ('pregnant', 'Gebe'), ('in_heat', 'Kızgınlık'), ('postpartum', 'Doğum Sonrası'), ('other', 'Diğer')], max_length=20, null=True, verbose_name='Kızgınlık Durumu')),
                ('insemination_date', models.DateField(blank=True, null=True, verbose_name='Tohumlama Tarihi')),
                ('sire_information', models.CharField(blank=True, max_length=200, null=True, verbose_name='Baba Bilgisi')),
                ('pregnancy_check_date', models.DateField(blank=True, null=True, verbose_name='Gebelik Kontrolü Tarihi')),
                ('is_pregnant', models.BooleanField(blank=True, null=True, verbose_name='Gebelik Durumu')),
                ('expected_birth_date', models.DateField(blank=True, null=True, verbose_name='Tahmini Doğum Tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproduction_records', to='hayvan.animal', verbose_name='Hayvan')),
            ],
            options={
                'verbose_name': 'Üreme Bilgisi',
                'verbose_name_plural': 'Üreme Bilgileri',
                'ordering': ['-record_date'],
            },
        ),
        migrations.AddField(
            model_name='birth',
            name='reproduction_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth', to='hayvan.reproductionrecord', verbose_name='Üreme Bilgisi'),
        ),
    ]
