# Generated by Django 5.2 on 2025-04-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hayvan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reproductionrecord',
            options={'ordering': ['-insemination_date'], 'verbose_name': 'Üreme Kaydı', 'verbose_name_plural': 'Üreme Kayıtları'},
        ),
        migrations.RenameField(
            model_name='birth',
            old_name='mother',
            new_name='animal',
        ),
        migrations.RemoveField(
            model_name='reproductionrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reproductionrecord',
            name='is_pregnant',
        ),
        migrations.RemoveField(
            model_name='reproductionrecord',
            name='reproductive_status',
        ),
        migrations.RemoveField(
            model_name='reproductionrecord',
            name='sire_information',
        ),
        migrations.AddField(
            model_name='animal',
            name='parent_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_animals', to='hayvan.birth', verbose_name='Doğum Kaydı'),
        ),
        migrations.AddField(
            model_name='birth',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Kolay'), ('normal', 'Normal'), ('difficult', 'Zor'), ('assisted', 'Yardımlı'), ('cesarean', 'Sezaryen')], default='normal', max_length=20, verbose_name='Doğum Zorluğu'),
        ),
        migrations.AddField(
            model_name='birth',
            name='veterinarian',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Veteriner'),
        ),
        migrations.AddField(
            model_name='reproductionrecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maliyet'),
        ),
        migrations.AddField(
            model_name='reproductionrecord',
            name='father_tag_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Baba Küpe No'),
        ),
        migrations.AddField(
            model_name='reproductionrecord',
            name='insemination_type',
            field=models.CharField(choices=[('natural', 'Doğal Aşım'), ('artificial', 'Suni Tohumlama')], default='natural', max_length=20, verbose_name='Tohumlama Tipi'),
        ),
        migrations.AddField(
            model_name='reproductionrecord',
            name='pregnancy_status',
            field=models.CharField(blank=True, choices=[('', 'Bilinmiyor'), ('pregnant', 'Gebe'), ('not_pregnant', 'Gebe Değil'), ('miscarriage', 'Düşük'), ('birth_completed', 'Doğum Yaptı')], default='', max_length=20, verbose_name='Gebelik Durumu'),
        ),
        migrations.AddField(
            model_name='reproductionrecord',
            name='semen_source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sperma Kaynağı'),
        ),
        migrations.AddField(
            model_name='reproductionrecord',
            name='technician',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teknisyen/Veteriner'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='reproduction_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth', to='hayvan.reproductionrecord', verbose_name='Üreme Kaydı'),
        ),
        migrations.AlterField(
            model_name='reproductionrecord',
            name='pregnancy_check_date',
            field=models.DateField(blank=True, null=True, verbose_name='Gebelik Kontrol Tarihi'),
        ),
        migrations.AlterField(
            model_name='reproductionrecord',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi'),
        ),
    ]
