# Generated by Django 5.2 on 2025-04-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hayvan', '0002_update_birth_and_reproduction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hayvan', 'verbose_name_plural': 'Hayvanlar'},
        ),
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='hayvan.animaltype', verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='hayvan.animalbreed', verbose_name='Irk'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tag_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Küpe Numarası'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ağırlık (kg)'),
        ),
    ]
